package apps;

import java.util.Scanner;

class NegativeNumberException extends Exception {
    public NegativeNumberException(String message) {
        super(message);
    }
}

public class FactorialCalculator {

    // Method that declares it can throw NegativeNumberException
    public static long factorial(int n) throws NegativeNumberException {
        if (n < 0) {
            // Throwing a custom exception
            throw new NegativeNumberException("Factorial is not defined for negative numbers!");
        }
        long fact = 1;
        for (int i = 1; i <= n; i++) {
            fact *= i;
        }
        return fact;
    }

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        try {
            System.out.print("Enter a number to find factorial: ");
            int num = sc.nextInt();

            // factorial() may throw NegativeNumberException
            long result = factorial(num);
            System.out.println("Factorial of " + num + " is: " + result);

        } catch (NegativeNumberException e) {
            System.out.println("Error: " + e.getMessage());
        } finally {
            sc.close();
            System.out.println("Program ended.");
        }
    }
}
